# config/config.yaml

# -----------------------------------------------------------------------------
# Reproducibility
# -----------------------------------------------------------------------------
seed: 42

# -----------------------------------------------------------------------------
# Logging & Checkpointing
# -----------------------------------------------------------------------------
log_dir: logs
experiment_name: coco_caption_run
log_every_n_steps: 50
enable_checkpointing: true

# -----------------------------------------------------------------------------
# DataInterface (COCO Caption) settings
# -----------------------------------------------------------------------------
dataset_class_name: coco
img_dir: ./data/coco
ann_dir: ./data/coco/annotations

batch_size: 32
test_batch_size: 32

num_workers: 4
persistent_workers: true

# -----------------------------------------------------------------------------
# Trainer args (will be picked up via inspect.signature)
# -----------------------------------------------------------------------------
max_epochs: 20
